In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_selection import f_regression, SelectKBest
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error,accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler, MinMaxScaler
from sklearn.feature_selection import RFECV
from sklearn.preprocessing import PolynomialFeatures
import warnings
import category_encoders as ce
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.exceptions import DataConversionWarning
from sklearn.preprocessing import StandardScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import mutual_info_regression,f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
import lightgbm as lgb

pd.options.display.max_columns = 100

/Users/chrislouie/anaconda3/lib/python3.7/site-packages/lightgbm/__init__.py:46: UserWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS is built by the Apple Clang (Xcode_8.3.3) compiler.
This means that in case of installing LightGBM from PyPI via the ``pip install lightgbm`` command, you don't need to install the gcc compiler anymore.
Instead of that, you need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.
You can install the OpenMP library by the following command: ``brew install libomp``.
  "You can install the OpenMP library by the following command: ``brew install libomp``.", UserWarning)

In [2]:
train = pd.read_csv('train_features.csv')
test_features = pd.read_csv('test_features.csv')
train_labels = pd.read_csv('train_labels.csv')
sample_submission = pd.read_csv('sample_submission.csv')

train, test_features.shape, train_labels.shape, sample_submission.shape

(          id  amount_tsh date_recorded                    funder  gps_height  \
 0      69572      6000.0    2011-03-14                     Roman        1390
 1       8776         0.0    2013-03-06                   Grumeti        1399
 2      34310        25.0    2013-02-25              Lottery Club         686
 3      67743         0.0    2013-01-28                    Unicef         263
 4      19728         0.0    2011-07-13               Action In A           0
 5       9944        20.0    2011-03-13       Mkinga Distric Coun           0
 6      19816         0.0    2012-10-01                      Dwsp           0
 7      54551         0.0    2012-10-09                     Rwssp           0
 8      53934         0.0    2012-11-03                  Wateraid           0
 9      46144         0.0    2011-08-03               Isingiro Ho           0
 10     49056         0.0    2011-02-20                   Private          62
 11     50409       200.0    2013-02-18                    Danida        1062
 12     36957         0.0    2012-10-14              World Vision           0
 13     50495         0.0    2013-03-15   Lawatefuka Water Supply        1368
 14     53752         0.0    2012-10-20                     Biore           0
 15     61848         0.0    2011-08-04                     Rudep        1645
 16     48451       500.0    2011-07-04                    Unicef        1703
 17     58155         0.0    2011-09-04                    Unicef        1656
 18     34169         0.0    2011-07-22                    Hesawa        1162
 19     18274       500.0    2011-02-22                    Danida        1763
 20     48375       200.0    2011-02-27                       Twe        2216
 21      6091         0.0    2013-02-10                      Dwsp           0
 22     58500         0.0    2011-10-04                    Unicef        1510
 23     37862       500.0    2013-11-03                       Isf         672
 24     51058         0.0    2013-01-21  African Development Bank        1645
 25     22308         0.0    2013-02-25    Government Of Tanzania        1273
 26     55012       500.0    2013-01-16                    Sobodo         200
 27     20145         0.0    2011-07-11                    Hesawa           0
 28     19685         0.0    2013-03-05    Government Of Tanzania        1443
 29     69124         0.0    2013-03-16   Lawatefuka Water Supply        1256
 ...      ...         ...           ...                       ...         ...
 59370  14796       200.0    2013-01-29                       NaN        1154
 59371  20387         0.0    2012-10-09               Netherlands           0
 59372  29940         0.0    2012-10-31                       Tlc           0
 59373  15233      5000.0    2013-01-30                     Rudep        1137
 59374  49651         0.0    2012-10-29                     Rwssp           0
 59375  50998     40000.0    2011-08-03    Government Of Tanzania          54
 59376  34716         0.0    2013-02-03                       NaN        1581
 59377  43986         0.0    2012-10-23    Government Of Tanzania           0
 59378  38067       500.0    2011-03-21                        Rc        2101
 59379  58255         0.0    2011-07-13                        Do           0
 59380  30647      6000.0    2011-03-14                     Roman        1439
 59381  67885         0.0    2011-03-16       Mkinga Distric Coun           0
 59382  47002         6.0    2013-08-03                 Ces(gmbh)        1383
 59383  44616         0.0    2013-01-19                World Bank          11
 59384  72148         0.0    2011-07-10                   Concern           0
 59385  34473       500.0    2012-11-03                     Jaica        1327
 59386  34952         0.0    2011-08-22                       Adb        1786
 59387  26640       100.0    2013-03-12                         0          25
 59388  72559         0.0    2013-01-29                     Kidep        1414
 59389  30410         0.0    2011-08-06                        Co         783
 59390  13677         0.0    2011-08-04                     Rudep        1715
 59391  44885         0.0    2013-08-03    Government Of Tanzania         540
 59392  40607         0.0    2011-04-15    Government Of Tanzania           0
 59393  48348         0.0    2012-10-27                   Private           0
 59394  11164       500.0    2011-03-09                World Bank         351
 59395  60739        10.0    2013-05-03           Germany Republi        1210
 59396  27263      4700.0    2011-05-07               Cefa-njombe        1212
 59397  37057         0.0    2011-04-11                       NaN           0
 59398  31282         0.0    2011-03-08                     Malec           0
 59399  26348         0.0    2011-03-23                World Bank         191

                   installer  longitude      latitude  \
 0                     Roman  34.938093 -9.856322e+00
 1                   GRUMETI  34.698766 -2.147466e+00
 2              World vision  37.460664 -3.821329e+00
 3                    UNICEF  38.486161 -1.115530e+01
 4                   Artisan  31.130847 -1.825359e+00
 5                       DWE  39.172796 -4.765587e+00
 6                      DWSP  33.362410 -3.766365e+00
 7                       DWE  32.620617 -4.226198e+00
 8                 Water Aid  32.711100 -5.146712e+00
 9                   Artisan  30.626991 -1.257051e+00
 10                  Private  39.209518 -7.034139e+00
 11                   DANIDA  35.770258 -1.057417e+01
 12             World vision  33.798106 -3.290194e+00
 13     Lawatefuka water sup  37.092574 -3.181783e+00
 14                   WEDECO  34.364073 -3.629333e+00
 15                      DWE  31.444121 -8.274962e+00
 16                      DWE  34.642439 -9.106185e+00
 17                      DWE  34.569266 -9.085515e+00
 18                      DWE  32.920154 -1.947868e+00
 19                    Danid  34.508967 -9.894412e+00
 20                      TWE  34.473430 -9.594990e+00
 21                      DWE   0.000000 -2.000000e-08
 22                      DWE  34.586901 -8.980014e+00
 23                      ISF  37.940029 -4.125595e+00
 24                      DWE  29.747066 -4.495568e+00
 25                      DWE  37.422751 -3.317536e+00
 26              Kilolo Star  39.370777 -9.942532e+00
 27                      DWE  31.104257 -1.735361e+00
 28         District council  37.611126 -3.263526e+00
 29     Lawatefuka water sup  37.061688 -3.191989e+00
 ...                     ...        ...           ...
 59370                   NaN  30.058731 -4.902633e+00
 59371                   DWE  33.586406 -3.040369e+00
 59372                   TLC  32.058548 -5.052101e+00
 59373                Distri  32.125024 -6.784358e+00
 59374                   DWE   0.000000 -2.000000e-08
 59375                   DWE  39.046942 -5.061494e+00
 59376                   NaN  34.821039 -5.076258e+00
 59377            Government  33.437012 -4.423594e+00
 59378                  ACRA  34.620387 -9.358405e+00
 59379                    DO  31.613284 -1.820226e+00
 59380                 Roman  34.942101 -9.849198e+00
 59381                   DWE  38.835001 -4.880204e+00
 59382                   DWE  37.454759 -3.323599e+00
 59383            World bank  39.626009 -1.005750e+01
 59384               CONCERN  30.667805 -2.483710e+00
 59385              JAICA CO  33.951681 -2.021854e+00
 59386                   DWE  31.738789 -8.532013e+00
 59387                     0  39.176480 -6.957098e+00
 59388                   DWE  30.692400 -3.593827e+00
 59389                   DWE  30.646486 -7.365418e+00
 59390                   DWE  31.370848 -8.258160e+00
 59391            Government  38.044070 -4.272218e+00
 59392            Government  33.009440 -8.520888e+00
 59393               Private  33.866852 -4.287410e+00
 59394              ML appro  37.634053 -6.124830e+00
 59395                   CES  37.169807 -3.253847e+00
 59396                  Cefa  35.249991 -9.070629e+00
 59397                   NaN  34.017087 -8.750434e+00
 59398                  Musa  35.861315 -6.378573e+00
 59399                 World  38.104048 -6.747464e+00

                         wpt_name  num_private                    basin  \
 0                           none            0               Lake Nyasa
 1                       Zahanati            0            Lake Victoria
 2                    Kwa Mahundi            0                  Pangani
 3           Zahanati Ya Nanyumbu            0  Ruvuma / Southern Coast
 4                        Shuleni            0            Lake Victoria
 5                         Tajiri            0                  Pangani
 6                     Kwa Ngomho            0                 Internal
 7                   Tushirikiane            0          Lake Tanganyika
 8              Kwa Ramadhan Musa            0          Lake Tanganyika
 9                        Kwapeto            0            Lake Victoria
 10                 Mzee Hokororo            0              Wami / Ruvu
 11              Kwa Alid Nchimbi            0               Lake Nyasa
 12                         Pamba            0                 Internal
 13          Kwa John Izack Mmari            0                  Pangani
 14                     Mwabasabi            0                 Internal
 15        Kwa Juvenal Ching'Ombe            0          Lake Tanganyika
 16               Kwa John Mtenzi            0                   Rufiji
 17               Kwa Rose Chaula            0                   Rufiji
 18                        Ngomee            0            Lake Victoria
 19                          none            0               Lake Nyasa
 20                          none            0               Lake Nyasa
 21                      Muungano            0            Lake Victoria
 22                       Shuleni            0                   Rufiji
 23                       Kinonga            0                  Pangani
 24                       Kamsasa            0          Lake Tanganyika
 25                     Kwa Tukai            0                  Pangani
 26         Ruhoma Primary School            0  Ruvuma / Southern Coast
 27                    Kwawilliam            0            Lake Victoria
 28                  Kwa Kibakaya            0                  Pangani
 29             Kwa Willium Kinda            0                  Pangani
 ...                          ...          ...                      ...
 59370             Village Office            0          Lake Tanganyika
 59371                   Ushirika            0            Lake Victoria
 59372           Kwa Mzee Kamanya            0          Lake Tanganyika
 59373                Kwa Kadiega            0               Lake Rukwa
 59374                 Nguvu Kazi            0            Lake Victoria
 59375                  Sekondari            0                  Pangani
 59376                    Nasingo            0                 Internal
 59377                       Fpct            0                 Internal
 59378             Michael Msigwa            0                   Rufiji
 59379            Coffee Plantati            0            Lake Victoria
 59380                       none            0               Lake Nyasa
 59381                 Mijohoroni            0                  Pangani
 59382             Kwa Luka Msaki            0                  Pangani
 59383                    Shuleni            0  Ruvuma / Southern Coast
 59384                   Chamkube            0            Lake Victoria
 59385                Kwa Marunda            0            Lake Victoria
 59386  Shule Ya Sekondari Katazi            0               Lake Rukwa
 59387                 Kwa Maliba            0              Wami / Ruvu
 59388         Kwa Philipo Kibeba            0          Lake Tanganyika
 59389                  Sekondari            0          Lake Tanganyika
 59390            Kwa Mzee Atanas            0          Lake Tanganyika
 59391                        Kwa            0                  Pangani
 59392             Benard Charles            0               Lake Rukwa
 59393                  Kwa Peter            0                 Internal
 59394                 Chimeredya            0              Wami / Ruvu
 59395        Area Three Namba 27            0                  Pangani
 59396          Kwa Yahona Kuvala            0                   Rufiji
 59397                    Mashine            0                   Rufiji
 59398                     Mshoro            0                   Rufiji
 59399            Kwa Mzee Lugawa            0              Wami / Ruvu

                subvillage         region  region_code  district_code  \
 0                Mnyusi B         Iringa           11              5
 1                 Nyamara           Mara           20              2
 2                 Majengo        Manyara           21              4
 3              Mahakamani         Mtwara           90             63
 4              Kyanyamisa         Kagera           18              1
 5             Moa/Mwereme          Tanga            4              8
 6           Ishinabulandi      Shinyanga           17              3
 7         Nyawishi Center      Shinyanga           17              3
 8              Imalauduki         Tabora           14              6
 9                Mkonomre         Kagera           18              1
 10                 Mizugo          Pwani           60             43
 11           Ngondombwito         Ruvuma           10              5
 12                Nkilifa      Shinyanga           17              2
 13                Omarini    Kilimanjaro            3              7
 14              Mwabasabi      Shinyanga           17              6
 15                  Tunzi          Rukwa           15              2
 16               Kidudumo         Iringa           11              4
 17                 Yeriko         Iringa           11              4
 18                 Center         Mwanza           19              1
 19               Manyanya         Iringa           11              5
 20                Majengo         Iringa           11              4
 21             Ibabachegu      Shinyanga           17              1
 22              Mkanivega         Iringa           11              4
 23             Mkonga Juu    Kilimanjaro            3              3
 24                  Msasa         Kigoma           16              3
 25               Kitereni    Kilimanjaro            3              4
 26                Shuleni          Lindi           80             23
 27              Chakahaya         Kagera           18              1
 28                  Kiyao    Kilimanjaro            3              1
 29                 Merali    Kilimanjaro            3              7
 ...                   ...            ...          ...            ...
 59370            Mazungwe         Kigoma           16              2
 59371             Chambwa      Shinyanga           17              2
 59372    Urambo Magharibi         Tabora           14              4
 59373           Mapambano          Rukwa           15              1
 59374          Mwamtani A      Shinyanga           17              1
 59375          Kwa Nyanji          Tanga            4              4
 59376                  Hu        Singida           13              2
 59377            Hospital         Tabora           14              2
 59378            Igelango         Iringa           11              4
 59379           Kaluyango         Kagera           18              3
 59380            Mnyusi B         Iringa           11              5
 59381           Mtakuja A          Tanga            4              8
 59382            Yamu Juu    Kilimanjaro            3              4
 59383           Mitumbati          Lindi           80             62
 59384          Songambele         Kagera           18             30
 59385             Mlimani           Mara           20              4
 59386               Nduza          Rukwa           15              2
 59387  Mtaa Wa Yangeyange  Dar es Salaam            7              2
 59388            Kumwambu         Kigoma           16              1
 59389             Itete B          Rukwa           15              3
 59390             Kitonto          Rukwa           15              2
 59391          Maore Kati    Kilimanjaro            3              3
 59392           Mbuyuni A          Mbeya           12              1
 59393             Masanga         Tabora           14              2
 59394            Komstari       Morogoro            5              6
 59395            Kiduruni    Kilimanjaro            3              5
 59396            Igumbilo         Iringa           11              4
 59397           Madungulu          Mbeya           12              7
 59398              Mwinyi         Dodoma            1              4
 59399        Kikatanyemba       Morogoro            5              2

                     lga                ward  population public_meeting  \
 0                Ludewa            Mundindi         109           True
 1             Serengeti               Natta         280            NaN
 2             Simanjiro             Ngorika         250           True
 3              Nanyumbu            Nanyumbu          58           True
 4               Karagwe          Nyakasimbi           0           True
 5                Mkinga                 Moa           1           True
 6       Shinyanga Rural              Samuye           0           True
 7                Kahama              Chambo           0           True
 8          Tabora Urban            Itetemia           0           True
 9               Karagwe              Kaisho           0           True
 10             Mkuranga             Tambani         345           True
 11             Namtumbo              Msindo         250           True
 12                Maswa            Busilili           0           True
 13                 Siha      Siha Kaskazini           1           True
 14                Meatu               Nkoma           0           True
 15     Sumbawanga Rural               Mkowe         200           True
 16               Njombe              Mdandu          35           True
 17               Njombe               Usuka          50           True
 18              Ukerewe            Ilangala        1000            NaN
 19               Ludewa             Mawengi           1           True
 20               Njombe              Matola           4           True
 21              Bariadi   Ikungulyabashashi           0            NaN
 22               Njombe               Usuka         350           True
 23                 Same            Kisiwani         210           True
 24         Kigoma Rural               Mkigo         156          False
 25          Moshi Rural             Kimochi         140           True
 26          Lindi Rural             Rutamba         260          False
 27              Karagwe           Nyaishozi           0           True
 28                Rombo        Mengwe Manda           1           True
 29                 Siha           Siha Kati           1           True
 ...                 ...                 ...         ...            ...
 59370            Kasulu              Rusesa           1           True
 59371             Maswa              Kulimi           0           True
 59372            Urambo              Urambo           0           True
 59373            Mpanda               Ilela          96           True
 59374           Bariadi              Sagata           0           True
 59375             Tanga             Mzizima         609           True
 59376     Singida Rural           Dung'unyi           1           True
 59377            Igunga              Nkinga           0           True
 59378            Njombe            Imalinyi          36           True

In [3]:
train['gps_height'].replace(0.0,np.nan,inplace=True)
test_features['gps_height'].replace(0.0,np.nan,inplace=True)
train['population'].replace(0.0,np.nan,inplace=True)
test_features['population'].replace(0.0,np.nan,inplace=True)
train['amount_tsh'].replace(0.0,np.nan,inplace=True)
test_features['amount_tsh'].replace(0.0,np.nan,inplace=True)
train['latitude'].replace(0.0,np.nan,inplace=True)
test_features['latitude'].replace(0.0,np.nan,inplace=True)
train['longitude'].replace(0.0,np.nan,inplace=True)
test_features['longitude'].replace(0.0,np.nan,inplace=True)
train['construction_year'].replace(0.0,np.nan,inplace=True)
test_features['construction_year'].replace(0.0,np.nan,inplace=True)

train.isna().sum()

id                           0
amount_tsh               41639
date_recorded                0
funder                    3635
gps_height               20438
installer                 3655
longitude                 1812
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population               21381
public_meeting            3334
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                    3056
construction_year        20709
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
dtype: int64

In [4]:
train['gps_height'].fillna(train.groupby(['region', 'district_code'])['gps_height'].transform('mean'), inplace=True)
train['gps_height'].fillna(train.groupby(['region'])['gps_height'].transform('mean'), inplace=True)
train['gps_height'].fillna(train['gps_height'].mean(), inplace=True)
train['population'].fillna(train.groupby(['region', 'district_code'])['population'].transform('median'), inplace=True)
train['population'].fillna(train.groupby(['region'])['population'].transform('median'), inplace=True)
train['population'].fillna(train['population'].median(), inplace=True)
train['amount_tsh'].fillna(train.groupby(['region', 'district_code'])['amount_tsh'].transform('median'), inplace=True)
train['amount_tsh'].fillna(train.groupby(['region'])['amount_tsh'].transform('median'), inplace=True)
train['amount_tsh'].fillna(train['amount_tsh'].median(), inplace=True)
train['latitude'].fillna(train.groupby(['region', 'district_code'])['latitude'].transform('mean'), inplace=True)
train['longitude'].fillna(train.groupby(['region', 'district_code'])['longitude'].transform('mean'), inplace=True)
train['longitude'].fillna(train.groupby(['region'])['longitude'].transform('mean'), inplace=True)
train['construction_year'].fillna(train.groupby(['region', 'district_code'])['construction_year'].transform('median'), inplace=True)
train['construction_year'].fillna(train.groupby(['region'])['construction_year'].transform('median'), inplace=True)
train['construction_year'].fillna(train.groupby(['district_code'])['construction_year'].transform('median'), inplace=True)
train['construction_year'].fillna(train['construction_year'].median(), inplace=True)

test_features['gps_height'].fillna(test_features.groupby(['region', 'district_code'])['gps_height'].transform('mean'), inplace=True)
test_features['gps_height'].fillna(test_features.groupby(['region'])['gps_height'].transform('mean'), inplace=True)
test_features['gps_height'].fillna(test_features['gps_height'].mean(), inplace=True)
test_features['population'].fillna(test_features.groupby(['region', 'district_code'])['population'].transform('median'), inplace=True)
test_features['population'].fillna(test_features.groupby(['region'])['population'].transform('median'), inplace=True)
test_features['population'].fillna(test_features['population'].median(), inplace=True)
test_features['amount_tsh'].fillna(test_features.groupby(['region', 'district_code'])['amount_tsh'].transform('median'), inplace=True)
test_features['amount_tsh'].fillna(test_features.groupby(['region'])['amount_tsh'].transform('median'), inplace=True)
test_features['amount_tsh'].fillna(test_features['amount_tsh'].median(), inplace=True)
test_features['latitude'].fillna(test_features.groupby(['region', 'district_code'])['latitude'].transform('mean'), inplace=True)
test_features['longitude'].fillna(test_features.groupby(['region', 'district_code'])['longitude'].transform('mean'), inplace=True)
test_features['longitude'].fillna(test_features.groupby(['region'])['longitude'].transform('mean'), inplace=True)
test_features['construction_year'].fillna(test_features.groupby(['region', 'district_code'])['construction_year'].transform('median'), inplace=True)
test_features['construction_year'].fillna(test_features.groupby(['region'])['construction_year'].transform('median'), inplace=True)
test_features['construction_year'].fillna(test_features.groupby(['district_code'])['construction_year'].transform('median'), inplace=True)
test_features['construction_year'].fillna(test_features['construction_year'].median(), inplace=True)

In [5]:
train['age'] = (2019 - train['construction_year']).astype(int)
test_features['age'] = (2019 - test_features['construction_year']).astype(int)

train_days_since = np.array(train['date_recorded'].values, dtype='datetime64')
test_days_since = np.array(test_features['date_recorded'].values,dtype='datetime64')

train_birth = round(train['construction_year'])
test_birth = round(test_features['construction_year'])

train_years_since = np.datetime_as_string(train_days_since, unit='Y')
test_years_since = np.datetime_as_string(test_days_since, unit='Y')

train_years_since = train_years_since.astype(int)
test_years_since = test_years_since.astype(int)

in_train_years = []
in_test_years = []

for i in range(0,len(train_years_since)):
    x = train_years_since[i] - train_birth[i]
    in_train_years.append(x)
    

for i in range(0,len(test_years_since)):
    x = test_years_since[i] - test_birth[i]
    in_test_years.append(x)
    
train['years_until_record'] = in_train_years
test_features['years_until_record'] = in_test_years

In [6]:
train['funder'].fillna('other',inplace=True)
train['installer'].fillna('other',inplace=True)
train['subvillage'].fillna('other',inplace=True)
train['public_meeting'].fillna('other',inplace=True)
train['scheme_management'].fillna('other',inplace=True)
train['scheme_name'].fillna('other',inplace=True)
train['permit'].fillna('other',inplace=True)
test_features['funder'].fillna('other',inplace=True)
test_features['installer'].fillna('other',inplace=True)
test_features['subvillage'].fillna('other',inplace=True)
test_features['public_meeting'].fillna('other',inplace=True)
test_features['scheme_management'].fillna('other',inplace=True)
test_features['scheme_name'].fillna('other',inplace=True)
test_features['permit'].fillna('other',inplace=True)

In [7]:
#functions for feature replacement
def top_funders(df):  
    if df['funder']=='Government Of Tanzania':
        return 'gov'
    elif df['funder']=='Danida':
        return 'danida'
    elif df['funder']=='Hesawa':
        return 'hesawa'
    elif df['funder']=='Rwssp':
        return 'rwssp'
    elif df['funder']=='World Bank':
        return 'world_bank'    
    elif df['funder']=='Kkkt':
        return 'Kkkt'
    elif df['funder']=='World Vision':
        return 'World Vision'
    elif df['funder']=='Unicef':
        return 'Unicef'
    elif df['funder']=='Tasaf':
        return 'Tasaf'
    elif df['funder']=='District Council':
        return 'District Council'
    elif df['funder']=='Dhv':
        return 'DHV_Engineering'
    elif df['funder']=='Norad':
        return 'NORAD'
    elif df['funder']=='Private Individual':
        return 'Private'
    elif df['funder']=='Dwsp':
        return 'DWSP'
    elif df['funder']=='Germany Republi':
        return 'Germany'
    elif df['funder']=='Ministry of Water':
        return 'Ministry of Water'
    elif df['funder']=='Water':
        return 'Ministry of Water'
    elif df['funder']=='Lga':
        return 'lga'
    else:
        return 'other'
    
def top_installers(df):
    if df['installer']=='DWE':
        return 'dwe'
    elif df['installer']=='Government':
        return 'gov'
    elif df['installer']=='RWE':
        return 'rwe'
    elif df['installer']=='Commu':
        return 'commu'
    elif df['installer']=='DANIDA':
        return 'danida'
    elif df['installer']=='KKKT':
        return 'kkkt'
    elif df['installer']=='Hesawa':
        return 'hesawa'
    elif df['installer']=='TCRS':
        return 'tcrs'
    elif df['installer']=='Central government':
        return 'Central government'
    elif df['installer']=='CES':
        return 'CES'
    elif df['installer']=='Community':
        return 'commu'
    elif df['installer']=='HESAWA':
        return 'hesawa'
    elif df['installer']=='District Council':
        return 'district_council'
    elif df['installer']=='World vision':
        return 'world_vision'
    elif df['installer']=='TASAF':
        return 'tasaf'
    elif df['installer']=='LGA':
        return 'lga'
    else:
        return 'other'

In [8]:
train['funder'] = train.apply(lambda x: top_funders(x),axis=1)
train['installer'] = train.apply(lambda x: top_installers(x),axis=1)
test_features['funder'] = test_features.apply(lambda x: top_funders(x),axis=1)
test_features['installer'] = test_features.apply(lambda x: top_installers(x),axis=1)

In [9]:
drop_these=[
    'date_recorded',
    'wpt_name',
    'recorded_by',
    'lga',
    'ward',
    'num_private',
    'subvillage',
    'waterpoint_type_group',
    'extraction_type_group',
    'extraction_type_class',
    'management',
    'payment',
    'quantity_group',
    'id',
    'source',
    'permit',
    'public_meeting',
    'scheme_name'
]
train.drop(columns=drop_these,inplace=True)
test_features.drop(columns=drop_these,inplace=True)

train.shape, test_features.shape

((59400, 24), (14358, 24))

# OKAY so i'm going to go ahead and attempt to stack my best scores on the public LB for Stage 1 stacking

### submission-016.csv (dart)
### submission-021.csv (gbrt)
### submission-022c.csv (rf)